ALTER TABLE dice_rolls ADD COLUMN die_one INTEGER NOT NULL DEFAULT 1 CHECK (die_one BETWEEN 1 AND 6);
ALTER TABLE dice_rolls ADD COLUMN die_two INTEGER NOT NULL DEFAULT 1 CHECK (die_two BETWEEN 1 AND 6);
ALTER TABLE dice_rolls ADD COLUMN is_double INTEGER NOT NULL DEFAULT 0 CHECK (is_double IN (0, 1));
ALTER TABLE dice_rolls ADD COLUMN roll_score INTEGER NOT NULL DEFAULT 0 CHECK (roll_score >= 0);
